#!/usr/bin/env perl
use warnings;
use strict;
use Term::ANSIColor;

if(@ARGV!=1) {
        # Version 1.0
        print "nyan-cat <file>\n";
        exit(1);
}

my $i=0;
my $j=0;

my @rainbow = ("bright_red","yellow","bright_yellow","bright_green","bright_blue","bright_magenta");
my $fileName = $ARGV[0];

open my $file, $fileName or die "NyanCat could not open $fileName : $!";
while( my $line = <$file>) {
        print colored($line,@rainbow[$i%6]);
        if($j == 2) {
                $j=0;
                $i+=1;
        }
        else {
                $j+=1;
        }
}
print "\n";

